### ISSUE TITLE
Peashooter and Peas

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#12]
I've noticed throughout testing, if the peashooter is trying to shoot something slightly below them, and terrain is in the way, since the Peashooters shoot straight, it gets stuck on the terrain. 

To counteract this, these two methods in conjunction could help:

- [x] Give the projectiles gravity (This would also prevent them from going off into space indefinetly)
- [x] Give the Peashooter the AI of a Skeleton, or some other ranged mob. (This could help the Peashooter aim better, because right now, any sort of strafe is enough to dodge them.)

**Comment by Lvgraef** [comment]
I dont see how the first point would help, it would drop and hit the block even earlier. I dont think its worth it to factor in the math so it aims up to avoid the block. unless thats already done by the skeletono ai but i dont think it is.
