### ISSUE TITLE
Seed Packets place on exact Y-Coordinate

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#15]
If you try and place a plant on a Grass Path, Slab or some other block with a height less than a block, it will place it inside of that block, in some cases, causing the plant to suffocate and die.

**Comment by Lvgraef** [comment]
well you wanted it to snap to the grid when placing it, i can make you unable to place it on non full blocks if you prefer?

**Comment by KaiCoyote** [comment]
Spawn Eggs snap to grid, but they place on correct Y-Axis

**Comment by Lvgraef** [comment]
ill make it like that then.
