### ISSUE TITLE
Issues Regarding Pea Crop

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#16]
- [x] Raw Peas are named "Peashooter Block"
- [x] Wild Peashooters can only spawn via bonemeal, not if the crop makes it to maturity naturally. (unless I'm just super unlucky but it felt really common with bonemeal compared to naturally growing).
- [x] Raw Peas and Cooked Peas should have the same eat speed, right now Cooked Peas are slower to eat, they should be fast like Raw Peas. 
- [x] Pea Pods can't be crafted down into Raw Peas. (1 Pea Pod = 3 Raw Peas)
- [x] Villager Pea Pod trade increases their level a little too much. (The other vanilla crop trades award 2 Villager XP according to the wiki.)
- [x] Villager Pea Pods have only 10 in stock (Should be 16 according to the wiki.)

**Comment by Lvgraef** [comment]
it didnt say it about the trades in the new doc? so not sure if im using the correct info ill change it tho
