### ISSUE TITLE
Buckets

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#28]
- [x] Every single bucket variety can now be worn
- [x] If a bucket has lost durability, it cant be used to collect liquids.
- [x] Empty Buckets no longer stack --- Is it possible to have them stack but the player can only equip one in the head slot, like a mob head, and if it has lost durability, it can't be placed back into an existing stack?

**Comment by Lvgraef** [comment]
> Every single bucket variety can now be worn

I am not quite sure what you mean by that.
