### ISSUE TITLE
Wall-nuts

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#31]
- [x] Wall-nuts can be knocked back by explosions
- [x] TNT when ignited spawns a primed TNT, but leaves the TNT block, creating an infinite loop of explosions.
- [x] For some reason, TNT explosions cause all the items exploded to drop, but still remain as blocks. (this could lead to item duping)
- [x] Placing blocks in their "protection-zone" causes damage to the Wall-nuts
- [x] Wall-nut hitboxes should be exactly 1x1x1. Their hitbox should also be solid, like that of boats. 
- [x] Wall-nuts are spawned in with Plant Armor (probably already aware just to lyk.)

**Comment by Lvgraef** [comment]
I cannot reproducing the placing of blocks causing damage.
