### ISSUE TITLE
Weird Wall-nut Protection Bug

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#32]
When a Wall-nut dies with a player in it, then the player tries to place blocks, it creates "ghost" blocks until it is corrected by being influenced by another Wall-nut.

**Comment by Lvgraef** [comment]
I cant reproduce this

**Comment by KaiCoyote** [comment]
It must've solved itself inbetween commits somehow, because I can't reproduce it either using the same methods as before.
