### ISSUE TITLE
Seed Packet Issues

### ISSUE THREAD

**Issue by KaiCoyote** [LopyLuna/Crops-n-Corpse#5]
- [x] They shouldn't be able to pick up non-tamed plants. 
- [x] Empty Seed Packets are stackable, but whilst containing a plant, they aren't.
- [x] In Creative Mode, they shouldn't become Empty Seed Packets when used. (Similar to Buckets)

**Comment by Lvgraef** [comment]
2 is intended behaviour. This is inline with all vanilla items like bowls and bottles

**Comment by KaiCoyote** [comment]
No, I mean like, middle-clicking a Peashooter Seed Packet will give you a stack of that item. If a seed packet contains a plant, it should only be able to stack to 1.
