### ISSUE TITLE
Browncoat & Imp seem to not respect Lightlevels?

### ISSUE THREAD

**Issue by ckocyigit** [LopyLuna/Crops-n-Corpse#55]
I had to disable cnc:imp and cnc:browncoat in KubeJS because these two entities were flooding our base with double-digit spawn rates.

Our base is fully illuminated, so I suspect they might not be affected by light levels or there could be another factor related to our base design—perhaps due to the use of mossy cobblestone or other similar blocks?

**Comment by James103** [comment]
I found the source of the issue; these two mobs specifically use a slightly different method to check whether they can spawn or not, which _ignores light levels_. `checkMobSpawnRules` checks for the light level, but `checkAnyLightMonsterSpawnRules` ignores it.

https://github.com/LopyLuna/Crops-n-Corpse/blob/751e4df79c0da5ff06190bd6deb26f645a087f84/src/main/java/uwu/llkc/cnc/common/events/ModEvents.java#L46-L48

**Comment by Lvgraef** [comment]
I think this was because they are meant to also spawn during the day. But i see the issue now, i will change it and have them not spawn during the day.

**Comment by Lvgraef** [comment]
Fixed
